import os
import shutil
import subprocess
import json
import hashlib

def get_sha256(filepath):
    h = hashlib.sha256()
    with open(filepath, 'rb') as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

def main():
    # repo_root is the directory containing this script
    repo_root = os.path.abspath(os.path.dirname(__file__))
    builds_dir = os.path.join(repo_root, "builds")
    src_dir = repo_root  # In GitHub Actions, the main repo root contains gradlew and the plugins
    
    # 1. Back up the old plugins.json
    old_plugins_json_path = os.path.join(builds_dir, "plugins.json")
    old_plugins = []
    if os.path.exists(old_plugins_json_path):
        try:
            with open(old_plugins_json_path, 'r', encoding='utf-8') as f:
                old_plugins = json.load(f)
            print(f"Loaded {len(old_plugins)} old plugins from backup.")
        except Exception as e:
            print(f"Warning: Failed to load old plugins.json: {e}")

    # 2. Run gradlew make --continue
    gradlew = os.path.join(src_dir, "gradlew")
    if os.name == 'nt':
        gradlew = gradlew + ".bat"
    
    print("Running gradlew make --continue...")
    subprocess.run([gradlew, "make", "--continue"], cwd=src_dir)
    
    # 3. Detect which plugins failed
    ignored_folders = {".git", ".github", ".vscode", "gradle", "temp_repos", "buildSrc", "Miro-Temp", "Phisher-Temp", "_patches", "builds"}
    plugins_in_src = []
    for item in os.listdir(src_dir):
        item_path = os.path.join(src_dir, item)
        if os.path.isdir(item_path) and item not in ignored_folders:
            if os.path.exists(os.path.join(item_path, "build.gradle.kts")):
                plugins_in_src.append(item)
                
    failed_plugins = []
    for plugin in plugins_in_src:
        build_dir = os.path.join(src_dir, plugin, "build")
        cs3_file = None
        if os.path.exists(build_dir):
            for file in os.listdir(build_dir):
                if file.endswith(".cs3"):
                    cs3_file = os.path.join(build_dir, file)
                    break
        if not cs3_file:
            failed_plugins.append(plugin)
            
    print(f"Failed plugins detected: {failed_plugins}")
    
    # 4. Disable failed plugins by renaming build.gradle.kts
    disabled_files = []
    for plugin in failed_plugins:
        gradle_file = os.path.join(src_dir, plugin, "build.gradle.kts")
        if os.path.exists(gradle_file):
            disabled_file = gradle_file + ".disabled"
            os.rename(gradle_file, disabled_file)
            disabled_files.append((gradle_file, disabled_file))
            
    # 5. Run gradlew makePluginsJson
    print("Generating plugins.json for successful plugins...")
    subprocess.run([gradlew, "makePluginsJson"], cwd=src_dir)
    
    # 6. Restore renamed build.gradle.kts files
    for original, disabled in disabled_files:
        if os.path.exists(disabled):
            os.rename(disabled, original)
            
    # 7. Merge old entries for failed plugins into the new plugins.json
    new_plugins_json_path = os.path.join(src_dir, "build", "plugins.json")
    if os.path.exists(new_plugins_json_path):
        try:
            with open(new_plugins_json_path, 'r', encoding='utf-8') as f:
                new_plugins = json.load(f)
        except Exception as e:
            print(f"Error loading new plugins.json: {e}")
            new_plugins = []
            
        new_plugins_map = {p["internalName"]: p for p in new_plugins}
        
        for plugin in failed_plugins:
            old_entry = None
            for p in old_plugins:
                if p["internalName"] == plugin or p["name"] == plugin:
                    old_entry = p
                    break
            if old_entry:
                dest_cs3 = os.path.join(builds_dir, f"{old_entry['internalName']}.cs3")
                if os.path.exists(dest_cs3):
                    old_entry["fileSize"] = os.path.getsize(dest_cs3)
                    old_entry["fileHash"] = f"sha256-{get_sha256(dest_cs3)}"
                if old_entry["internalName"] not in new_plugins_map:
                    new_plugins.append(old_entry)
                    print(f"Merged old entry for failed plugin: {plugin}")
                    
        # Write merged plugins.json back
        with open(new_plugins_json_path, 'w', encoding='utf-8') as f:
            json.dump(new_plugins, f, indent=4, ensure_ascii=False)
            print("Successfully merged and saved plugins.json.")
    else:
        print("Error: new plugins.json was not generated by Gradle.")

if __name__ == "__main__":
    main()
